apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-web-deploy
  labels:
    app: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: simple-web
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80       
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web
spec:
  selector:
    app: simple-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
